"use client";

export default function PrivacyPolicy() {
  return (
    <div style={{ background: "#fff", color: "#1a1a1a", minHeight: "100vh", fontFamily: "'DM Sans', sans-serif" }}>
      <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet" />

      <header style={{ padding: "2rem 1rem", textAlign: "center", borderBottom: "1px solid #eee" }}>
        <a href="/" style={{ textDecoration: "none", display: "inline-flex", alignItems: "center", gap: "0.75rem" }}>
          <img src="/logo-256-transparent.png" alt="VirtualLotus" style={{ width: 40, height: 40 }} />
          <span style={{ fontFamily: "Cormorant Garamond, serif", fontSize: "1.5rem", fontWeight: 400, color: "#1a1a1a", letterSpacing: "0.05em" }}>VirtualLotus</span>
        </a>
      </header>

      <main style={{ maxWidth: 720, margin: "0 auto", padding: "2rem 1.5rem 4rem", lineHeight: 1.8, fontSize: "0.92rem" }}>
        <h1 style={{ fontFamily: "Cormorant Garamond, serif", fontSize: "2rem", fontWeight: 400, marginBottom: "0.5rem" }}>Privacy Policy</h1>
        <p style={{ color: "#666", fontSize: "0.82rem", marginBottom: "2rem" }}>Last updated: May 16, 2026</p>

        <p><strong>Data Controller:</strong> AUCUSTOM, Nederhorst 54, 7608 JX Almelo, Netherlands<br />
        <strong>Email:</strong> info@virtual-lotus.com<br />
        <strong>KvK:</strong> 95187111<br />
        <strong>BTW:</strong> NL005135718B81</p>

        <p>For the purposes of the General Data Protection Regulation (GDPR), AUCUSTOM is the Data Controller. For all data protection matters, you can contact our Privacy Lead at info@virtual-lotus.com.</p>

        <h2 style={h2}>2. What VirtualLotus Is</h2>
        <p>VirtualLotus is an AI companion platform. Users can have conversations with AI-powered characters for emotional support and companionship.</p>
        <p><strong>VirtualLotus is NOT a medical service, therapy, counseling, or crisis intervention tool.</strong> If you are in crisis, contact emergency services (112 in the EU) or a local crisis helpline (see <a href="#crisis" style={link}>Section 13</a>).</p>

        <h2 style={h2}>3. What Data We Collect</h2>

        <h3 style={h3}>3.1 Account Data</h3>
        <p><strong>Email address</strong> — used for authentication via secure magic link. We do not use or store passwords.</p>

        <h3 style={h3}>3.2 Usage Data</h3>
        <p><strong>IP address</strong> — used for rate limiting and abuse prevention. Not linked to your identity.</p>
        <p><strong>Browser language</strong> — used to display the interface in your preferred language.</p>
        <p><strong>Message counts</strong> — used for daily and lifetime usage limits. We do not store message content long-term.</p>

        <h3 style={h3}>3.3 Chat Data</h3>
        <p><strong>Chat messages</strong> — processed in real time by our AI providers to generate responses. Messages are held temporarily in server memory during your session and are automatically deleted after the session ends. They are not stored in our database.</p>

        <h3 style={h3}>3.4 Payment Data</h3>
        <p><strong>Subscription plan and status</strong> — stored to provide access to paid features.</p>
        <p><strong>Stripe Customer ID and Subscription ID</strong> — stored to manage your subscription.</p>
        <p><strong>Credit card details are never stored by us.</strong> All payments are processed by Stripe. See <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer" style={link}>Stripe&apos;s Privacy Policy</a>.</p>

        <h3 style={h3}>3.5 Generated Images</h3>
        <p><strong>Image prompts and generated images</strong> — stored to track usage limits. Images are generated by OpenAI&apos;s GPT Image API. You may request deletion at any time.</p>

        <h3 style={h3}>3.6 Profile Data</h3>
        <p><strong>Premium status and plan information</strong> — stored to provide the correct features.</p>

        <h2 style={h2}>4. Why We Collect Data (Legal Basis)</h2>
        <p>We process your data based on:</p>
        <p><strong>Contract performance</strong> (Art. 6(1)(b)) — to provide the VirtualLotus service.</p>
        <p><strong>Legitimate interest</strong> (Art. 6(1)(f)) — rate limiting, abuse prevention, security.</p>
        <p><strong>Consent</strong> (Art. 6(1)(a)) — for optional cookies or analytics (if used).</p>
        <p><strong>Image generation</strong> — processed under Art. 6(1)(b) to provide the image feature.</p>

        <h2 style={h2}>5. Sub-processors</h2>
        <div style={{ overflowX: "auto", marginBottom: "1.5rem" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.85rem" }}>
            <thead>
              <tr style={{ borderBottom: "2px solid #ddd", textAlign: "left" }}>
                <th style={th}>Service</th>
                <th style={th}>Purpose</th>
                <th style={th}>Location</th>
              </tr>
            </thead>
            <tbody>
              <tr style={tr}><td style={td}>Supabase</td><td style={td}>Authentication, database</td><td style={td}>EU (AWS Ireland)</td></tr>
              <tr style={tr}><td style={td}>Stripe</td><td style={td}>Payment processing</td><td style={td}>USA</td></tr>
              <tr style={tr}><td style={td}>Anthropic</td><td style={td}>AI chat (Claude)</td><td style={td}>USA</td></tr>
              <tr style={tr}><td style={td}>OpenAI</td><td style={td}>Image generation</td><td style={td}>USA</td></tr>
              <tr style={tr}><td style={td}>Vercel</td><td style={td}>Website hosting</td><td style={td}>USA</td></tr>
              <tr style={tr}><td style={td}>Cloudflare</td><td style={td}>DNS, security</td><td style={td}>USA</td></tr>
              <tr style={tr}><td style={td}>Zoho</td><td style={td}>Business email</td><td style={td}>EU / India</td></tr>
            </tbody>
          </table>
        </div>
        <p><strong>International transfers:</strong> Some sub-processors are located in the USA. All transfers are protected by Standard Contractual Clauses (SCCs) or equivalent safeguards.</p>

        <h2 style={h2}>6. Data Retention</h2>
        <p><strong>Account data</strong> — kept as long as your account exists. Deleted upon request.</p>
        <p><strong>Chat messages</strong> — temporary only; deleted after your session ends.</p>
        <p><strong>Payment records</strong> — retained for 7 years (Dutch tax law).</p>
        <p><strong>Usage counters</strong> — reset daily or kept for lifetime limits.</p>
        <p><strong>Generated images</strong> — stored until you request deletion or close your account.</p>

        <h2 style={h2}>7. Your Rights (GDPR)</h2>
        <p>You have the right to: <strong>access</strong> your data, <strong>rectify</strong> inaccurate data, <strong>erase</strong> your data (&quot;right to be forgotten&quot;), <strong>restrict</strong> processing, <strong>data portability</strong>, <strong>object</strong> to processing based on legitimate interest, and <strong>withdraw consent</strong> at any time.</p>
        <p>To exercise your rights, email: <strong>info@virtual-lotus.com</strong>. We respond within 30 days.</p>
        <p>If you are not satisfied, you may lodge a complaint with the <a href="https://www.autoriteitpersoonsgegevens.nl/" target="_blank" rel="noopener noreferrer" style={link}>Dutch Data Protection Authority</a>.</p>

        <h2 style={h2}>8. Cookies</h2>
        <p><strong>Essential cookies</strong> — required for authentication and session management.</p>
        <p><strong>Local storage</strong> — used for theme preference. Stored only on your device.</p>
        <p>We do <strong>not</strong> use tracking, analytics, or advertising cookies.</p>

        <h2 style={h2}>9. Children</h2>
        <p>VirtualLotus is not intended for users under 16. If you believe a child under 16 has created an account, contact us and we will delete it.</p>

        <h2 style={h2}>10. Security</h2>
        <p>We implement technical and organizational measures including: encrypted connections (HTTPS/TLS), Row Level Security (RLS) in our database, separate admin access keys, and no storage of payment card details.</p>
        <p>We follow the principle of data minimization — we only collect what is necessary.</p>

        <h2 style={h2}>11. Changes to This Policy</h2>
        <p>We may update this Privacy Policy. Significant changes will be announced on our website. The &quot;Last updated&quot; date shows the latest revision.</p>

        <h2 style={h2}>12. Contact</h2>
        <p><strong>AUCUSTOM</strong><br />
        Nederhorst 54, 7608 JX Almelo, Netherlands<br />
        Email: info@virtual-lotus.com<br />
        KvK: 95187111<br />
        BTW: NL005135718B81</p>

        <h2 style={h2} id="crisis">13. Crisis Resources</h2>
        <p>VirtualLotus is not a crisis service. If you or someone you know is in immediate danger, contact emergency services or one of the following helplines:</p>

        <div style={{ overflowX: "auto", marginBottom: "1.5rem" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.85rem" }}>
            <thead>
              <tr style={{ borderBottom: "2px solid #ddd", textAlign: "left" }}>
                <th style={th}>Region</th>
                <th style={th}>Service</th>
                <th style={th}>Contact</th>
              </tr>
            </thead>
            <tbody>
              <tr style={tr}><td style={td}><strong>EU</strong></td><td style={td}>Emergency</td><td style={td}>112</td></tr>
              <tr style={tr}><td style={td}><strong>USA / Canada</strong></td><td style={td}>Emergency</td><td style={td}>911</td></tr>
              <tr style={tr}><td style={td}><strong>UK</strong></td><td style={td}>Emergency</td><td style={td}>999</td></tr>
              <tr style={tr}><td style={td}><strong>Netherlands</strong></td><td style={td}>113 Zelfmoordpreventie</td><td style={td}>0900-0113 / <a href="https://www.113.nl/" target="_blank" rel="noopener noreferrer" style={link}>113.nl</a></td></tr>
              <tr style={tr}><td style={td}><strong>Netherlands</strong></td><td style={td}>De Kindertelefoon</td><td style={td}>0800-0432</td></tr>
              <tr style={tr}><td style={td}><strong>UK</strong></td><td style={td}>Samaritans</td><td style={td}>116 123 / <a href="https://www.samaritans.org/" target="_blank" rel="noopener noreferrer" style={link}>samaritans.org</a></td></tr>
              <tr style={tr}><td style={td}><strong>UK</strong></td><td style={td}>SHOUT</td><td style={td}>Text SHOUT to 85258</td></tr>
              <tr style={tr}><td style={td}><strong>Germany</strong></td><td style={td}>Telefonseelsorge</td><td style={td}>0800 111 0 111</td></tr>
              <tr style={tr}><td style={td}><strong>France</strong></td><td style={td}>Suicide prevention</td><td style={td}>3114</td></tr>
              <tr style={tr}><td style={td}><strong>Poland</strong></td><td style={td}>Centrum Wsparcia</td><td style={td}>800 70 2222</td></tr>
              <tr style={tr}><td style={td}><strong>Spain</strong></td><td style={td}>Teléfono de la Esperanza</td><td style={td}>717 003 717</td></tr>
              <tr style={tr}><td style={td}><strong>USA</strong></td><td style={td}>988 Suicide &amp; Crisis Lifeline</td><td style={td}>988</td></tr>
              <tr style={tr}><td style={td}><strong>Canada</strong></td><td style={td}>Talk Suicide Canada</td><td style={td}>1-833-456-4566</td></tr>
              <tr style={tr}><td style={td}><strong>Australia</strong></td><td style={td}>Lifeline</td><td style={td}>13 11 14</td></tr>
              <tr style={tr}><td style={td}><strong>Japan</strong></td><td style={td}>TELL Lifeline</td><td style={td}>03-5774-0992</td></tr>
              <tr style={tr}><td style={td}><strong>South Korea</strong></td><td style={td}>Crisis Line</td><td style={td}>1577-0199</td></tr>
              <tr style={tr}><td style={td}><strong>International</strong></td><td style={td}>IASP Directory</td><td style={td}><a href="https://www.iasp.info/resources/Crisis_Centres/" target="_blank" rel="noopener noreferrer" style={link}>iasp.info</a></td></tr>
            </tbody>
          </table>
        </div>

        <p style={{ textAlign: "center", fontStyle: "italic", color: "#666", marginTop: "2rem" }}>You are never alone. Help is available 24/7.</p>
      </main>

      <footer style={{ textAlign: "center", padding: "1.5rem", color: "#999", fontSize: "0.72rem", borderTop: "1px solid #eee" }}>
        <a href="/terms" style={{ color: "#999", textDecoration: "none", marginRight: "1.5rem" }}>Terms of Service</a>
        <a href="/privacy" style={{ color: "#999", textDecoration: "none" }}>Privacy Policy</a>
        <div style={{ marginTop: "0.5rem" }}>© {new Date().getFullYear()} VirtualLotus by AUCUSTOM</div>
      </footer>
    </div>
  );
}

const h2: React.CSSProperties = { fontFamily: "Cormorant Garamond, serif", fontSize: "1.3rem", fontWeight: 400, marginTop: "2.5rem", marginBottom: "0.75rem", paddingBottom: "0.25rem", borderBottom: "1px solid #eee" };
const h3: React.CSSProperties = { fontSize: "0.95rem", fontWeight: 500, marginTop: "1.5rem", marginBottom: "0.5rem" };
const link: React.CSSProperties = { color: "#8b6b5a", textDecoration: "underline" };
const th: React.CSSProperties = { padding: "0.5rem 0.75rem", fontWeight: 500 };
const td: React.CSSProperties = { padding: "0.5rem 0.75rem" };
const tr: React.CSSProperties = { borderBottom: "1px solid #eee" };